### ISSUE TITLE
Update Ubuntu ISO to 22.04.4

### ISSUE THREAD

**Issue by Delte** [zentyal/iso-generator#2]
https://github.com/zentyal/iso-generator/blob/f5aadef7390f5be65ada31886a4892bc3f579ae7/autoinstall-vars.conf.template#L11

**Comment by djoven89** [comment]
Thank you @Delte, we have updated the ISO version as you can see in [this commit](https://github.com/zentyal/iso-generator/commit/f91a95ebda66cbfa4f2ecb35fce333ffc858e8f8)
